# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

working_dir: &working_dir
  working_directory: ~/repo

environment: &environment
  MAVEN_OPTS: -Xmx3200m

restore_cache: &restore_cache
  keys:
    - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
    - v1-dependencies-

save_cache: &save_cache
  paths:
    - ~/.m2
  key: v1-dependencies-{{ checksum "pom.xml" }}

chrome_binary_download: &chrome_binary_download
  - run:
    name: make sure chrome binary is available
    command: | 
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      which google-chrome
      export PATH=/home/circleci/repo/target/classes/drivers:$PATH
      wget  https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip
      sudo mv chromedriver /usr/bin/chromedriver
      sudo chown root:root /usr/bin/chromedriver
      sudo chmod 777 /usr/bin/*chrome*




version: 2
jobs:
  run_centoscore:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      # Download and cache dependencies
      - *restore_cache
      - run: mvn dependency:go-offline
      - *save_cache
      - *chrome_binary_download
      
      - run: 
          name: Install Selenium
          command: |
            wget https://selenium-release.storage.googleapis.com/3.13/selenium-server-standalone-3.13.0.jar
            wget http://www.java2s.com/Code/JarDownload/testng/testng-6.8.7.jar.zip
            unzip testng-6.8.7.jar.zip
      - run:
          name: Stand up xvfb
          command: |
            nohup Xvfb :99 > /dev/null 2>&1 &
            #nohup /usr/bin/Xvfb :6 -ac -screen 0 1024x768x16  -fbdir /tmp &
      - run:
          name: Run Selenium - dashboardtests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=dashboard
          when: always
      - run:
          name: Run Selenium - issuestests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=issues
          when: always
      - run:
          name: Run Selenium - navigationtest
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=navigation
          when: always
      - run:
          name: Run Selenium - pdftests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=pdf
          when: always
      - run:
          name: Run Selenium - pagestests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=pages
          when: always
      - run:
          name: Run Selenium - projectsettingstests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=projectsettings
          when: always
      - run:
          name: Run Selenium - reporttestsscope
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=reporttestsscope
          when: always
      - run:
          name: Run Selenium - reporttestsscript
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=reporttestscript
          when: always
      - run:
          name: Run Selenium - reporttestsmisc
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=reporttestsmisc
          when: always
      - run:
          name: Run Selenium - rescantest
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=rescan
          when: always
      - run:
          name: Run Selenium - scansettingstests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=scansettings
          when: always
      - run:
          name: Run Selenium - scanstests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=scans
          when: always
      - run:
          name: Run Selenium - systemsettingstests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=systemsettings
          when: always
      - run:
          name: Run Selenium - templatetests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=template
          when: always
      - run:
          name: Run Selenium - testingstandardtests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=testingstandard
          when: always
      - run:
          name: Run Selenium - userlogintest
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=userlogin
          when: always
      - run:
          name: Run Selenium - usermanagementtests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=usermanagement
          when: always
      - run:
          name: Run Selenium - organizationsettingstests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=organizationsettings
          when: always
      - run:
          name: Run Selenium - pagegroupstests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=pagegroups
          when: always 
      - run:
          name: Run Selenium - readonlyaccesstests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=readonlyaccess
          when: always
      - run:
          name: Run Selenium - issuetrackertests
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=issuetracker
          when: always
      - run:
          name: Run Selenium - schedulescans
          command: |
            nohup xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-3.13.0.jar 2>&1 &
            nohup google-chrome --headless 2>&1 &
            mvn test -DappUrl=https://comply-qa-centos-core.dequelabs.com -DadminUserName=admin@deque.com -DadminPassword=f@ncy7201toaster -DdefaultPassword=deque -Dgroups=schedulescans
          when: always     
      - store_artifacts:
          path: ~/repo/Reports
          
workflows:
    version: 2
    regression:
        jobs:
            - run_centoscore:
                requires:
                    - start_run_centoscore
            - start_run_centoscore:
                type: approval    
